### ISSUE TITLE
default value of "last-day" = today, should point to yesterday

### ISSUE THREAD

**Issue by sfirke** [r-hub/cranlogs#19]
When I call `cran_downloads()` it gives me the data for today, which is always 0 downloads.
```
library(cranlogs)
cran_downloads()
#>         date count
#> 1 2017-02-08     0
```

This isn't a problem in when I specify `interval = "last-week"`:
```
library(cranlogs)
cran_downloads(NULL, "last-week")
#>         date   count
#> 1 2017-02-01 1205129
#> 2 2017-02-02 1139361
#> 3 2017-02-03 1106105
#> 4 2017-02-04  570183
#> 5 2017-02-05  571141
#> 6 2017-02-06 1129596
#> 7 2017-02-07 1253377
```

**Comment by gaborcsardi** [comment]
Yeah.

**Comment by Breza** [comment]
I was just about to post the same issue.

**Comment by gaborcsardi** [comment]
The SQL script looks good to me, maybe there is an extra 0 in the db? If that's the case, then we either need to fix the update script not to add that, or change the SQL script not to include 0-days when calculating the max day, here: https://github.com/metacran/cranlogs.app/blob/d51bd2bfaf78491666450e0cda91336760629ae7/db/proc.sql#L18

**Comment by maelle** [comment]
and why does it work different for last-week and last-month? right now `cran_downloads(when = "last-week")` gives me days up to the 9th of April whereas last-day gives me the 11th of April.

**Comment by gaborcsardi** [comment]
IDK

**Comment by gaborcsardi** [comment]
The SQL code and the DB are actually fine: 
```
cranlogs=# SELECT MAX(day) FROM daily;
    max
------------
 2019-04-09
```

**Comment by gaborcsardi** [comment]
This is probably the issue: https://github.com/metacran/cranlogs.app/blob/d51bd2bfaf78491666450e0cda91336760629ae7/routes/downloads.js#L131

**Comment by maelle** [comment]
Ok so this should be the current date minus one day, but in last-week shouldn't the last day be the 10th instead of the 9th?

**Comment by gaborcsardi** [comment]
> Ok so this should be the current date minus one day

no, that might not be there yet, either

**Comment by maelle** [comment]
oh ok so today, we'd expect all intervals including last-day to go until the 9th.

**Comment by gaborcsardi** [comment]
or 10th, or 11th it really depends on when the data is updated and which time zone you are in

**Comment by maelle** [comment]
:+1:

**Comment by gaborcsardi** [comment]
I think `last-day` can just be the last day for which data is available.

**Comment by maelle** [comment]
and last-week/last-month 7/30 days prior to that, right? (which they seem to be now) I can update the docs but I'm not sure where to update the code, the js or SQL after all?

**Comment by maelle** [comment]
thanks! I :eyes:  the fix http://r-hub.github.io/cranlogs/#usage

**Comment by maelle** [comment]
@gaborcsardi I've updated the docs see
https://r-hub.github.io/cranlogs/#usage
https://r-hub.github.io/cranlogs/reference/cran_downloads.html#details
