### ISSUE TITLE
`cran_downloads()` throws an error

### ISSUE THREAD

**Issue by sn248** [r-hub/cranlogs#27]
I am trying to use the `cranlogs` package, but currently `cran_downloads()` is throwing the following error

```
No encoding supplied: defaulting to UTF-8.
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^
```

Thanks

**Comment by maelle** [comment]
was it a transient API problem? I don't get this error today.

**Comment by gaborcsardi** [comment]
Please reopen if you still see this.

**Comment by sn248** [comment]
Thank you, it works now!
