### ISSUE TITLE
`cran_downloads` now working?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-hub/cranlogs#42]
Maybe this is a temporary problem, but I noticed that download counts are 0 for the 1st of Sept.

``` r
cranlogs::cran_downloads(
  packages = "ggplot2",
  from = "2019-08-30",
  to = "2019-09-01"
)
#>         date count package
#> 1 2019-08-30 27377 ggplot2
#> 2 2019-08-31 13531 ggplot2
#> 3 2019-09-01     0 ggplot2
```

<sup>Created on 2019-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
September is not available yet: http://cran-logs.rstudio.com/
Hopefully it is coming soon.

**Comment by gaborcsardi** [comment]
Good now.
