### ISSUE TITLE
package name errors in CRAN logs

### ISSUE THREAD

**Issue by lindbrook** [r-hub/cranlogs#49]
There are 8 problem package names in the RStudio's CRAN mirror download logs. They arguably shouldn't appear in the logs because they are either misspelled, typos, or are no longer on CRAN or in the Archive.

pkg.name.errors <- c("calib", "clus", "ebayesthresh", "PARccs", "rcom",
  "RcppTemplate", "rmosek", "tsp")

lapply(pkg.name.errors, function(x) cranlogs::cran_downloads(x, "last-month"))

'calib' is neither on CRAN nor in the archive (9 yrs old).
'clus' is probably some kind of typo.
'ebayesthresh' is an old name for 'EbayesThresh', which is on CRAN.
'PARccs'is an old name for 'pARccs', which is now archived.
'rcom' is neither on CRAN nor in the archive (7 yrs old).
'RcppTemplate' is neither on CRAN nor in the archive (10 yrs old).
'rmosek' is an old name for 'Rmosek', which is on CRAN.
'tsp'is an old name for 'TSP', which is on CRAN.

**Comment by gaborcsardi** [comment]
Right. Unfortunately there is no way for us to fix this in cranlogs. If you want to clean the DB, you'll need to use external information, just like you did.

**Comment by lindbrook** [comment]
For what it's worth, the problematic package names are also related to r-hub/cranlogs#45: if it were possible to (optionally) exclude downloads of a certain size (e.g., < 1000 bytes), the problematic package names would essentially "go away". 

To make the case for doing so, I hope to post an update about the _systematic_ aspect of 500 bytes package downloads to r-hub/cranlogs#45 in the next day or so. If this (optional) filtering would be impractical for computational or coding reasons, let me know.

**Comment by gaborcsardi** [comment]
@lindbrook great, I'll try to fix #45 then. 

Do you think we should clean the whole DB now, or just make sure that the new data is clean?

**Comment by lindbrook** [comment]
I think the whole is better than this point forward.
