### ISSUE TITLE
Default "from" to the CRAN release date

### ISSUE THREAD

**Issue by ikashnitsky** [r-hub/cranlogs#51]
Quite often one would like to see the whole history of package downloads. 
The information on initial releases is available here
https://cran.r-project.org/web/packages/available_packages_by_date.html
Maybe there is a cheap way to wrap and lookup this table?

**Comment by gaborcsardi** [comment]
You can easily write a wrapper with pkgsearch, you can get the date of the last release like this:
```
tail(pkgsearch::cran_package_history("igraph")$date, 1)
```

**Comment by ikashnitsky** [comment]
Great!
In this case the date of the first release would be more interesting, I think
```
head(pkgsearch::cran_package_history("igraph")$date, 1)
```
Don't you think the initial release would be a meaningful `from` default for `cranlogs::cran_downloads`?

**Comment by gaborcsardi** [comment]
Why would you have downloads _before_ the first release?

**Comment by ikashnitsky** [comment]
```
head(pkgsearch::cran_package_history("igraph")$date, 1)
```
gives the first date the package appears on CRAN

**Comment by ikashnitsky** [comment]
So, You don't think that would be a nice starting default? (the whole CRAN history of a package)

**Comment by gaborcsardi** [comment]
We can't just change the default values, because that is not backward compatible. You can always put in `from = "1980-01-01"` to get all downloads for a package.

**Comment by ikashnitsky** [comment]
I see. Thanks for taking care to explain
