### ISSUE TITLE
R-version for packages download statistics

### ISSUE THREAD

**Issue by jangorecki** [r-hub/cranlogs#70]
Knowing what R versions users of your package are using is quite useful information. Obtaining this information via cranlogs is currently not possible. Raw data on cran-logs.rstudio.com does contain such field, so this information could be provided.

http://cran-logs.rstudio.com/
```
Each file contents the following variables:

date
time (in UTC)
size (in bytes)
r_version, version of R used to download package
r_arch (i386 = 32 bit, x86_64 = 64 bit)
r_os (darwin9.8.0 = mac, mingw32 = windows)
package
country, two letter ISO country code. Geocoded from IP using [MaxMind's](http://dev.maxmind.com/geoip/legacy/geolite) free database
ip_id, a daily unique id assigned to each IP address
```

**Comment by gaborcsardi** [comment]
Indeed. Unfortunately that would require a new database schema, and it would also make the size of the database much bigger, so we would need to move to a bigger machine.
